- name: "Create systemd service"
  import_tasks: service/systemd.yml

- name: "Creating link to service"
  when: existing_service.stat.exists == False
  file:
    src: "{{ crackerjack.destination }}/data/config/service/crackerjack.service"
    dest: "/etc/systemd/system/crackerjack.service"
    state: link

- name: "Enabling and starting service"
  service:
    name: crackerjack
    enabled: true
    state: started
