- name: "Create systemd service"
  import_tasks: service/systemd.yml

# In Ubuntu 16 we have to copy the file, otherwise we get the following error:
#     > Unable to enable service crackerjack: Failed to execute operation: Too many levels of symbolic links
- name: "Creating link to service"
  when: existing_service.stat.exists == False
  copy:
    src: "{{ crackerjack.destination }}/data/config/service/crackerjack.service"
    dest: "/etc/systemd/system/crackerjack.service"
    remote_src: yes

- name: "Enabling and starting service"
  service:
    name: crackerjack
    enabled: true
    state: started
