- name: Install Ubuntu service
  import_tasks: ubuntu/18-20.yml
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == '20'

- name: Install Ubuntu service
  import_tasks: ubuntu/18-20.yml
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == '18'

- name: Install Ubuntu service
  import_tasks: ubuntu/16.yml
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == '16'

- name: Install Ubuntu service
  import_tasks: ubuntu/14.yml
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == '14'

- name: Install CentOS pre-requisites
  import_tasks: centos/8.yml
  when: ansible_distribution|lower == 'centos' and ansible_distribution_major_version == '8'

- name: Install CentOS pre-requisites
  import_tasks: centos/7.yml
  when: ansible_distribution|lower == 'centos' and ansible_distribution_major_version == '7'