- name: Generate certificates
  import_tasks: ssl/certificates.yml

- name: Configure web server for Ubuntu
  import_tasks: ubuntu/server.yml
  when: ansible_distribution|lower == 'ubuntu'

- name: Configure web server for CentOS
  import_tasks: centos/server.yml
  when: ansible_distribution|lower == 'centos'